import { Inter } from "next/font/google";
import "./globals.css";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "@/components/ui/menubar"
import { Button } from "@/components/ui/button"
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fetchGenres = async () => {
  const res = await fetch(`${process.env.API_URL}/3/genre/movie/list`, {
    headers : {
      authorization : `Bearer ${process.env.API_ACCESS_TOKEN}`
    }
  })
  const data = await res.json()
  return data
}

export default async function RootLayout({ children }) {
  const data = await fetchGenres()
  return (
    <html lang="en">
			<body className={inter.className}>
				<div className="container mt-4">
					<Menubar>
						<h1 className="mx-4">Next Movie</h1>
					</Menubar>

					<main className="mt-4">
            <div className="flex">
            <div className="w-[250px] pr-4 border-r">
            <Link href={'/'}>
            <Button variant="ghost" className="w-full justify-start">All Movies</Button>
            </Link>
            {data.genres.map(genre => {
              return <Link key={genre.id} href={`/genres/${genre.name}/${genre.id}`}>
                <Button 
                    variant="ghost"
                    className="w-full justify-start">
                    {genre.name}
                </Button>
                </Link>;
                })}
            </div>
                <div className="pt-4"> {children}</div>
            </div>
          </main>
				</div>
			</body>
		</html>
  );
}
