import { Inter } from "next/font/google";
import "./globals.css";

import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { redirect } from "next/navigation";
import GenreButton from "@/components/GenreButton";
import CustomMenuBar from "@/components/CustomMenuBar";
import AuthProvider from "./context/AuthProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fetchGenres = async () => {
  const res = await fetch(`${process.env.API_URL}/3/genre/movie/list`, {
    headers: {
      authorization: `Bearer ${process.env.API_ACCESS_TOKEN}`,
    },
  });
  const data = await res.json();
  return data;
};

export default async function RootLayout({ children }) {
  const data = await fetchGenres();
  async function search(FormData) {
    "use server";
    const q = FormData.get("q");
    redirect(`/search?q=${q}`);
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="container mt-4">
            <div className="flex gap-2 flex-wrap">
              <div className="w-full flex justify-between items-center">
                <h3>Next Movie</h3>
                <CustomMenuBar />
              </div>
              <form action={search} className="flex flex-grow-0 gap-3">
                <Input type="text" name="q" />
                <Button>Search</Button>
              </form>
            </div>
            <main className="mt-4">
              <div className="flex">
                <div className="w-[250px] sticky top-0 pr-6 border-r">
                  <Link href={"/"}>
                    <Button variant="ghost" className="w-full justify-start">
                      All Movies
                    </Button>
                  </Link>
                  {data.genres.map((genre) => {
                    return (
                      <Link
                        key={genre.id}
                        href={`/genres/${genre.name}/${genre.id}`}
                      >
                        <GenreButton genre={genre} />
                      </Link>
                    );
                  })}
                </div>
                <div className="px-4 w-full h-full overflow-scroll">
                  {" "}
                  {children}
                </div>
              </div>
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
